spring.application.name=Atmos

# MySQL Connection - Fixed with security flags
spring.datasource.url=jdbc:mysql://localhost:3306/atmos_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=@nand01SQL

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Server Port
server.port=8080